M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu20.04.1} date mar 14 feb 2023 16:49:47
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-14T16:49:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0610
%
G90
G05
T1
X5.7559Y-2.611
X5.7559Y-2.989
T0
M30
